@startuml
'https://plantuml.com/class-diagram
scale 1000 width

class Main{}

abstract class Analyzer {
	# Input input
	# Map<Token, String> nextPotentialCharacters
	# AnalyzerFactory analyzerFactory
	# String nextPotentialCharactersString
	
	+ {abstract} void analyze(TokenBase tokenBase)
    + {abstract} void setNextAnalyzer()
    + String getNextPotentialCharactersString()
}

class TokenBase {
	- List<Lexeme> lexemes
	- int index

	+ Lexeme getLexeme()
	+ boolean incrementIndex()
}

interface Token {
}

class AnalyzerFactory {
	- Map<Token, Analyzer> tokenAnalyzerMap
	+ Analyzer getAnalyzerForToken(Token token)
}

class Input {
	- String input
	- int index

	+ boolean hasToken()
	+ char getNextChar()
}

class ColonAnalyzer extends Analyzer {}

class CommaAnalyzer extends Analyzer {}

class KeyStringAnalyzer extends Analyzer {}

class LeftBraceAnalyzer extends Analyzer {}

class LeftBracketAnalyzer extends Analyzer {}

class RightBraceAnalyzer extends Analyzer {}

class RightBracketAnalyzer extends Analyzer {}

class StringAnalyzer extends Analyzer {}

class ValueAnalyzer extends Analyzer {}

AnalyzerFactory -down- Analyzer
Analyzer -right- TokenBase
Analyzer -left- Input
AnalyzerFactory -right- Token
Main -- Analyzer

@enduml