@startuml
'https://plantuml.com/class-diagram
class Main{}

interface Parser {
	Lexeme parse(List<Lexeme> lexemes)
}

class Lexeme {
	- Token tokenType
	- Object value
	- int start, end
}

Lexeme -left- Parser
Main -right- Parser

@enduml